---
# defaults file for chrony
public_ntp_servers:
  - time.google.com
  - time1.google.com
  - time2.google.com
  - time3.google.com
  - time4.google.com

chrony_package: default
chrony_service: default
chrony_dir: default
chrony_filename: default
