---
- name: Upgrade all packages
  tags: [mariadb]
  yum:
    name: '*' 
    state: latest

- name: Add MariaDB GPG key
  tags: [mariadb, mariadb-repository]
  rpm_key:
    key: http://mirror1.cl.netactuate.com/mariadb/yum/RPM-GPG-KEY-MariaDB
    state: present

- name: Add MariaDB repository
  tags: [mariadb, mariadb-repository]
  yum_repository:
    name: MariaDB
    description: MariaDB YUM repo
    baseurl: https://mirror1.cl.netactuate.com/mariadb/yum/{{ mariadb_server_version }}/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}-{{ mariadb_server_architecture }}
    gpgcheck: 1

- name: Install MariaDB Server
  tags: [mariadb]
  yum:
    name: mariadb-server
    state: present
  notify: start mariadb server

- name: Ensure MariaDB Server is running after reboot
  tags: [mariadb]
  service:
    name: mariadb
    enabled: yes
