---
- name: Add MariaDB GPG key
  tags: [mariadb]
  rpm_key:
    key: http://mirror1.cl.netactuate.com/mariadb/yum/RPM-GPG-KEY-MariaDB
    state: present

- name: Add MariaDB repository
  tags: [mariadb]
  yum_repository:
    name: MariaDB
    description: MariaDB YUM repo
    baseurl: https://mirror1.cl.netactuate.com/mariadb/yum/{{ mariadb_server_version }}/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}-{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}
    gpgcheck: 1

- name: Install MariaDB Server
  tags: [mariadb]
  yum:
    name: mariadb-server
    state: present
    update_cache: true
