---
- name: Override Chrony defaults for Debian systems
  set_fact:
    chrony_service:  "{{ (chrony_service   == 'DEFAULT')  | ternary ('chronyd',       chrony_service) }}"
    chrony_package:  "{{ (chrony_package   == 'DEFAULT')  | ternary ('chrony',        chrony_package) }}"
    chrony_dir:      "{{ (chrony_dir       == 'DEFAULT')  | ternary ('/etc/chrony/',  chrony_dir) }}"
    chrony_filename: "{{ (chrony_filename  == 'DEFAULT')  | ternary ('chrony.conf',   chrony_filename) }}"
