---
- name: Override Chrony defaults for Debian systems.
  set_fact:
    chrony_service: chronyd
    chrony_package: chrony
    chrony_dir: /etc/chrony/
  when: chrony_dir == 'DEFAULT' and ansible_pkg_mgr == 'apt'
