---
- name: Install Chorny - Debian based distributions
  tags: chrony
  apt:
    name: chrony
    state: present
    update_cache: true
    cache_valid_time: 3600
  when: ansible_pkg_mgr == 'apt'

- name: Install Chrony - RedHat based distributions
  tags: chrony
  yum:
    name: chrony
    state: present
    update_cache: true
  when: ansible_pkg_mgr == 'yum'
