---
# tasks file for chrony

- name: Install chrony
  tags: chrony
  package:
    name: chrony
    state: present
    update_cache: true

- name: Upload chrony.conf template
  tags: [chrony, chrony-config]
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  notify: Restart chrony
  
- name: Restart chrony
  become: true
  tags: [chrony,chrony-config,chrony-restart]
  command: /bin/true
  notify: Restart chrony
