---
# tasks file for chrony

- include_tasks: validate.yml

- name: Load the Debian specific defaults
  include_tasks: debian.yml
  when: ansible_pkg_mgr == 'apt'

- name: Load the RedHat specific defaults
  include_tasks: redhat.yml
  when: ansible_pkg_mgr == 'yum'

- include_tasks: install.yml
- include_tasks: configure.yml
