---
# tasks file for chrony

- include_tasks: validate.yml
- include_tasks: install.yml
- include_tasks: configure.yml

- name: Restart chrony
  become: true
  tags: [chrony, chrony-config, chrony-restart]
  command: /bin/true
  notify: Restart chrony
  when: ansible_pkg_mgr == 'apt'

- name: Restart chronyd
  become: true
  tags: [chrony, chrony-config, chrony-restart]
  command: /bin/true
  notify: Restart chronyd
  when: ansible_pkg_mgr == 'yum'
