---
# tasks file for chrony
- include_tasks: install.yml
- include_tasks: configure.yml

- name: Restart chrony
  become: true
  tags: [chrony,chrony-config,chrony-restart]
  command: /bin/true
  notify: Restart chrony
