---

# System-specific files only set facts.
# For this reason, we run (one of) them before validation.

- name: Load the Debian specific defaults
  tags: [ chrony, chrony-config, chrony-validate ]
  include_tasks: debian.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: Load the RedHat specific defaults
  tags: [ chrony, chrony-config, chrony-validate ]
  include_tasks: redhat.yml
  when: ansible_facts['os_family'] == 'RedHat'

- include_tasks: validate.yml
  tags: [ chrony, chrony-config, chrony-validate ]

- include_tasks: install.yml
  tags: [ chrony ]

- include_tasks: configure.yml
  tags: [ chrony, chrony-config ]
