---
# Validate file for chrony role

- name: Validate if the public_ntp_servers is not none
  tags: [chrony, chrony-validate]
  assert:
    that: public_ntp_servers is not none
    fail_msg: "public_ntp_servers is not set"
    success_msg: "The item public_ntp_servers is defined"
