---
# Validate variables used by this role

- name: Validate if the chrony_servers is not none
  tags: always
  assert:
    that: chrony_servers is not none and ( chrony_servers | length > 0)
    fail_msg: "chrony_servers is not set or empty"
    success_msg: "chrony_servers is defined and not empty"
